language: cpp

matrix:
  allow_failures:
    - python: 3.5
    - python: 3.6
  include:
    - python: 3.5
      env: PY=py
      before_install: choco install python --version 3.5.4
    - python: 3.6
      env: PY=py
      before_install: choco install python --version 3.6.8
    - python: 3.7
      env: PY=py
      before_install: choco install python

jobs:
  include:
    - stage: build
      os: linux
      sudo: required
      dist: trusty
      before_install: false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - ninja-build
      env: COMPILER=g++-7
      script: ./tools/build_lib.sh

    - stage: build
      os: windows
      name: "Build lib win"
      env:
        - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
      script:
        - export PATH=$MSBUILD_PATH:$PATH
        - ./tools/build_lib.bat

    - stage: build
      os: windows
      name: "Build Python 3.6 win"
      python: 3.6
      env:
        - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
        - PYTHON=3.6
      script:
        - export PATH=$MSBUILD_PATH:$PATH
        - ./tools/build_python.bat
