language: cpp
jobs:
  include:
  - stage: build
    os: linux
    sudo: required
    dist: trusty
    before_install: false
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
        - ninja-build
    env: COMPILER=g++-7
    script: "./tools/build_lib.sh"
  - stage: build
    os: windows
    name: Build lib win
    env:
    - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
    script:
    - export PATH=$MSBUILD_PATH:$PATH
    - "./tools/build_lib.bat"
  - stage: build
    os: windows
    name: Build Python 3.6 win
    python: 3.6
    env:
    - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
    - PYTHON=3.6
    script:
    - choco install python --version 3.6.8
    - export PATH="c:\Python36":"C:\Python36\Scripts":$MSBUILD_PATH:$PATH
    - pip install argparse setuptools
    - pip uninstall wheel
    - pip install wheel
    - python -c "import setuptools; print(setuptools.__version__)"
    - "./tools/build_python.bat"
    deploy:
      provider: releases
      api_key:
        secure: s+dcD1Zs8GOJTH58D0cmHYvXoeFDzlxBYrhMaioqeTibJqNJPIcSC2rPt9DuqH7L+j33NMMLgVX3cfwiDbGnP+2v1tL2eY+QbIXhTnlLbx+t/rwy6uqap5Y5PpZqErHZodEdjjnfL1+beX1JC2yY9B5YokezSSwuiRTh3NQpF+F8wmy3fN46hb0H1TSga400fW4lNunhZzy6zMNraclZ9AWQAiQhYuH900Ov2Act0BbzHd8ri6BsOcpDM1cJgM98P9i3xM7SbZdyM3PayWeH/cV35L5JBMvvDJeSg91nBV3hY5IOaLqknO7iCYpsZMmx+lDINcFzO9C0iliZhsmJgAO8C93F+rNesHYAuZ7UY+sqXz+DGFa+ycORRRk7KvlRvyFFYTF3AptE5PqNcnSPVqj0ixz/14EFRYsI2t90u5d8JCKO9KpKM0KoluUt3IjSsVcpYEKojXankqCGPmQ/kfbWSEGDc9Jyxq0P8bGzLf6VR1JiQX//sEOQDSQfBTDAlISjS6PLeL06kvX3zi2vmfUsMvAFxGIh99gSQK1E18Lq+bYuic/KvjLgv0LWZ1PcQeYf8elEt0BsMRP4d+D+0O/+t2YK+OPbhzzojMEgtB9h90q7Kakh2VPjSif8txUTkgPnI5tC6zkwiJ0WFUCMp79KsBkwopVVOgKksIUobpk=
      skip_cleanup: true
      file_glob: true
      file: bin/dist/lepy-*.whl
      on:
        repo: toodef/light-engine
      draft: true

  - stage: build
    os: windows
    name: Build Python 3.7 win
    python: 3.7
    env:
    - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
    - PYTHON=3.7
    script:
    - choco install python --version 3.7.2
    - export PATH="c:\Python37":"C:\Python37\Scripts":$MSBUILD_PATH:$PATH
    - pip install setuptools argparse
    - pip uninstall wheel
    - pip install wheel
    - "./tools/build_python.bat"
    - dir bin/dist
    deploy:
      provider: releases
      api_key:
        secure: s+dcD1Zs8GOJTH58D0cmHYvXoeFDzlxBYrhMaioqeTibJqNJPIcSC2rPt9DuqH7L+j33NMMLgVX3cfwiDbGnP+2v1tL2eY+QbIXhTnlLbx+t/rwy6uqap5Y5PpZqErHZodEdjjnfL1+beX1JC2yY9B5YokezSSwuiRTh3NQpF+F8wmy3fN46hb0H1TSga400fW4lNunhZzy6zMNraclZ9AWQAiQhYuH900Ov2Act0BbzHd8ri6BsOcpDM1cJgM98P9i3xM7SbZdyM3PayWeH/cV35L5JBMvvDJeSg91nBV3hY5IOaLqknO7iCYpsZMmx+lDINcFzO9C0iliZhsmJgAO8C93F+rNesHYAuZ7UY+sqXz+DGFa+ycORRRk7KvlRvyFFYTF3AptE5PqNcnSPVqj0ixz/14EFRYsI2t90u5d8JCKO9KpKM0KoluUt3IjSsVcpYEKojXankqCGPmQ/kfbWSEGDc9Jyxq0P8bGzLf6VR1JiQX//sEOQDSQfBTDAlISjS6PLeL06kvX3zi2vmfUsMvAFxGIh99gSQK1E18Lq+bYuic/KvjLgv0LWZ1PcQeYf8elEt0BsMRP4d+D+0O/+t2YK+OPbhzzojMEgtB9h90q7Kakh2VPjSif8txUTkgPnI5tC6zkwiJ0WFUCMp79KsBkwopVVOgKksIUobpk=
      skip_cleanup: true
      file_glob: true
      file: bin/dist/lepy-*.whl
      on:
        repo: toodef/light-engine
      draft: true

  - stage: build
    os: windows
    name: Build Python 3.5 win
    python: 3.5
    env:
    - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
    - PYTHON=3.5
    script:
    - choco install python --version 3.5.4
    - export PATH="c:\Python35":"C:\Python35\Scripts":"C:\Python36\Scripts":$MSBUILD_PATH:$PATH
    - python -m pip install --upgrade pip
    - pip install setuptools argparse
    - pip uninstall -y setuptools
    - pip install setuptools
    - pip uninstall -y wheel
    - pip install wheel
    - "./tools/build_python.bat"
    deploy:
      provider: releases
      api_key:
        secure: s+dcD1Zs8GOJTH58D0cmHYvXoeFDzlxBYrhMaioqeTibJqNJPIcSC2rPt9DuqH7L+j33NMMLgVX3cfwiDbGnP+2v1tL2eY+QbIXhTnlLbx+t/rwy6uqap5Y5PpZqErHZodEdjjnfL1+beX1JC2yY9B5YokezSSwuiRTh3NQpF+F8wmy3fN46hb0H1TSga400fW4lNunhZzy6zMNraclZ9AWQAiQhYuH900Ov2Act0BbzHd8ri6BsOcpDM1cJgM98P9i3xM7SbZdyM3PayWeH/cV35L5JBMvvDJeSg91nBV3hY5IOaLqknO7iCYpsZMmx+lDINcFzO9C0iliZhsmJgAO8C93F+rNesHYAuZ7UY+sqXz+DGFa+ycORRRk7KvlRvyFFYTF3AptE5PqNcnSPVqj0ixz/14EFRYsI2t90u5d8JCKO9KpKM0KoluUt3IjSsVcpYEKojXankqCGPmQ/kfbWSEGDc9Jyxq0P8bGzLf6VR1JiQX//sEOQDSQfBTDAlISjS6PLeL06kvX3zi2vmfUsMvAFxGIh99gSQK1E18Lq+bYuic/KvjLgv0LWZ1PcQeYf8elEt0BsMRP4d+D+0O/+t2YK+OPbhzzojMEgtB9h90q7Kakh2VPjSif8txUTkgPnI5tC6zkwiJ0WFUCMp79KsBkwopVVOgKksIUobpk=
      skip_cleanup: true
      file_glob: true
      file: bin/dist/lepy-*.whl
      on:
        repo: toodef/light-engine
      draft: true
